[package]
name = "mirrorx_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
redis = { version = "0.21.5", features = [
    "r2d2",
    "tokio-comp",
    "connection-manager",
] }
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.17.0", features = ["full"] }
anyhow = "1.0.57"
ring = "0.16.20"
base64 = "0.13.0"
once_cell = "1.10.0"
rand = "0.8.5"
regex = "1.5.6"
